### ISSUE TITLE
`undefined method` issue with JRuby publisher

### ISSUE THREAD

**Issue by hsbt** [sigstore/sigstore-ruby#189]
**Description**

👋  I got the following error with trusted publisher used by JRuby.

https://github.com/ruby/psych/actions/runs/12115672565/job/33774497380#step:8:58

```
ERROR:  While executing gem ... (NoMethodError)
    undefined method `public_to_der' for #<OpenSSL::PKey::EC:0x650d5a3d>
Did you mean?  public_method
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/sigstore-0.2.1/lib/sigstore/verifier.rb:286:in `verify_sct'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/sigstore-0.2.1/lib/sigstore/verifier.rb:264:in `block in verify_scts'
	org/jruby/RubyArray.java:1981:in `each'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/sigstore-0.2.1/lib/sigstore/verifier.rb:263:in `verify_scts'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/sigstore-0.2.1/lib/sigstore/signer.rb:1[54](https://github.com/ruby/psych/actions/runs/12115672565/job/33774497380#step:8:58):in `verify_chain'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/sigstore-0.2.1/lib/sigstore/signer.rb:43:in `sign'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/sigstore-cli-0.2.1/lib/sigstore/cli.rb:95:in `sign'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/sigstore-cli-0.2.1/lib/sigstore/cli.rb:13:in `start'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/gems/shared/gems/sigstore-cli-0.2.1/exe/sigstore-cli:5:in `<main>'
	org/jruby/RubyKernel.java:1220:in `load'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/commands/exec_command.rb:225:in `load!'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/commands/exec_command.rb:74:in `execute'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/command.rb:326:in `invoke_with_build_args'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/command_manager.rb:253:in `invoke_command'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/command_manager.rb:194:in `process_args'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/command_manager.rb:152:in `run'
	/home/runner/.rubies/jruby-9.4.8.0/lib/ruby/stdlib/rubygems/gem_runner.rb:[57](https://github.com/ruby/psych/actions/runs/12115672565/job/33774497380#step:8:61):in `run'
	/home/runner/.rubies/jruby-9.4.8.0/bin/gem:12:in `<main>'
```

**Version**

sigstore-0.2.1 and release-gem@1.1.0.

**Comment by segiddins** [comment]
JRuby is unsupported due to numerous issues with jruby-openssl, let me disable for jruby on release-gem

**Comment by segiddins** [comment]
ah the push still succeeded but the attesting failed, again because jruby-openssl isn't fully compatible with the OpenSSL module interface

**Comment by hsbt** [comment]
Yes, `gem push` is succeeded with JRuby. Can we disable only sigstore feature with JRuby?

**Comment by headius** [comment]
We do plan to fix these things... just nobody available to work on them right now!

**Comment by segiddins** [comment]
I've been working on getting around this in https://github.com/sigstore/sigstore-ruby/pull/192
